# Generated by Django 4.2.5 on 2023-09-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0002_remove_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email",
        ),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="", max_length=128, unique=True),
        ),
    ]
