# Generated by Django 4.2.5 on 2023-09-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media_root/guests/')),
                ('property_picture', models.ImageField(blank=True, null=True, upload_to='media_root/guests/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('origin_country', models.IntegerField(blank=True, null=True)),
                ('language', models.IntegerField(blank=True, null=True)),
                ('dietary_restrictions', models.IntegerField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('target_dates', models.JSONField(blank=True, default=dict, null=True)),
                ('num_guests', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
