# Generated by Django 4.2.5 on 2023-09-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configset',
            name='config_id',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='ConfigSet',
        ),
    ]
