# Generated by Django 4.2.5 on 2023-09-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0002_remove_configset_config_id_delete_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media_root/hosts/')),
                ('property_picture', models.ImageField(blank=True, null=True, upload_to='media_root/hosts/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('origin_country', models.IntegerField(blank=True, null=True)),
                ('language', models.IntegerField(blank=True, null=True)),
                ('dietary_restrictions', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('available_dates', models.JSONField(blank=True, default=dict, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
